name: Deploy BradleyhouseApp
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code and check
        uses: actions/checkout@v4

      - name: Add app_offline
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "./stop_app/app_offline.htm"
          
      - name: Stop App 
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          state-name: ../.ftp-deploy-sync-state.json
          # Deployment destination server & path. Formatted as protocol://domain.com:port/full/destination/path/
          server: ${{ secrets.ftp_host }}
          # FTP account username
          username: ${{secrets.ftp_username }}
          # FTP account password
          password: ${{ secrets.password }}
          # The local folder to copy, defaults to root project folder
          local-dir: ./stop_app/
          server-dir: ./httpdocs/

      - name: edit connection string
        uses: benday-inc/edit-dbconnstr-in-appsettings@main
        with:
          pathtosettingsfile: '${{ github.workspace }}/appsettings.json'
          name: "local"
          connectionstring: ${{ secrets.ConnectionString}}

      - name: Setup .net
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: 7.0.x

      - name: restore Dependency
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Publish
        run:  dotnet publish -c Release --output ./Release
        
      - name: sync files (FTP Deploy)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.password }}
          local-dir: ./Release/
          server-dir: ./httpdocs/



            
      
    
