name: Deploy BradleyhouseApp
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code and check
        uses: actions/checkout@v4

      - name: edit connection string
        uses: benday-inc/edit-dbconnstr-in-appsettings@main
        with:
          pathtosettingsfile: '${{ github.workspace }}/Bradleyhouse/appsettings.json'
          name: "local"
          connectionstring: "Server=(local); Database=demo123; Trusted_Connection=True;"

      - name: Setup .net
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: 7.0.x

      - name: restore Dependency
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Publish
        run:  dotnet publish -c Release --output ./Release

      - name: sync files (FTP Deploy)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.password }}
          local-dir: ./Release/
          server-dir: ./httpdocs/
          
      
    
