name: Deploy BradleyhouseApp
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Add app_offline
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "./stop_app/app_offline.htm"
          
      - name: Upload app_offline
        uses: bayssmekanique/action-simple-file-upload@v2
        with:
          user: ${{ secrets.ftp_username }}
          password: ${{ secrets.password }}
          host: ${{ secrets.ftp_host  }}
          src: ./stop_app/app_offline.htm
          dest: ./httpdocs/
          
      - name: Get latest code and check
        uses: actions/checkout@v4

      - name: edit connection string
        uses: benday-inc/edit-dbconnstr-in-appsettings@main
        with:
          pathtosettingsfile: '${{ github.workspace }}/appsettings.json'
          name: "local"
          connectionstring: ${{ secrets.ConnectionString}}

      - name: Setup .net
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: 7.0.x

      - name: restore Dependency
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Publish
        run:  dotnet publish -c Release --output ./Release
        
      - name: sync files (FTP Deploy)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.password }}
          local-dir: ./Release/
          server-dir: ./httpdocs/

      - name: Clean ReactJS precache-manifest and logs
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ secrets.ftp_host }}
          user: ${{ secrets.ftp_username }}
          password: ${{ secrets.password }}
          remoteFiles: "app_offline.htm"
          workingDir: "./httpdocs/"

            
      
    
